# Part1-Data Preprocessing

In [1]:
#Step1- Importing Libraries for Preprocessing

In [2]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [3]:
#Step2- Import Dataset

In [4]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_a99c6d0855af49bb9994160c61640388 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='dB0aIJ8MytU714CqQe6ABZMPwGgZEewfL_102wJmjx3A',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_a99c6d0855af49bb9994160c61640388.get_object(Bucket='deeplearning-donotdelete-pr-t7g9gcnhvk3euu',Key='diabetes.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()



Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
5              5      116             74              0        0  25.6   
6              3       78             50             32       88  31.0   
7             10      115              0              0        0  35.3   
8              2      197             70             45      543  30.5   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
11            10      168             74              0        0  38.0   
12            10      139             80              0        0  27.1   
13             1      189             60             23      846  30.1   
14             5      166             72             19      175  25.8   
15             7      100              0              0        0  30.0   
16             0      118             84             47      230  45.8   
17             7      107             74              0        0  29.6   
18             1      103             30             38       83  43.3   
19             1      115             70             30       96  34.6   
20             3      126             88             41      235  39.3   
21             8       99             84              0        0  35.4   
22             7      196             90              0        0  39.8   
23             9      119             80             35        0  29.0   
24            11      143             94             33      146  36.6   
25            10      125             70             26      115  31.1   
26             7      147             76              0        0  39.4   
27             1       97             66             15      140  23.2   
28            13      145             82             19      110  22.2   
29             5      117             92              0        0  34.1   
..           ...      ...            ...            ...      ...   ...   
738            2       99             60             17      160  36.6   
739            1      102             74              0        0  39.5   
740           11      120             80             37      150  42.3   
741            3      102             44             20       94  30.8   
742            1      109             58             18      116  28.5   
743            9      140             94              0        0  32.7   
744           13      153             88             37      140  40.6   
745           12      100             84             33      105  30.0   
746            1      147             94             41        0  49.3   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   
752            3      108             62             24        0  26.0   
753            0      181             88             44      510  43.3   
754            8      154             78             32        0  32.4   
755            1      128             88             39      110  36.5   
756            7      137             90             41        0  32.0   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
760      

In [6]:
x=dataset.iloc[:,0:8]

In [7]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
5              5      116             74              0        0  25.6   
6              3       78             50             32       88  31.0   
7             10      115              0              0        0  35.3   
8              2      197             70             45      543  30.5   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
11            10      168             74              0        0  38.0   
12            10      139             80              0        0  27.1   
13             1      189             60             23      846  30.1   
14             5      166             72             19      175  25.8   
15             7      100              0              0        0  30.0   
16             0      118             84             47      230  45.8   
17             7      107             74              0        0  29.6   
18             1      103             30             38       83  43.3   
19             1      115             70             30       96  34.6   
20             3      126             88             41      235  39.3   
21             8       99             84              0        0  35.4   
22             7      196             90              0        0  39.8   
23             9      119             80             35        0  29.0   
24            11      143             94             33      146  36.6   
25            10      125             70             26      115  31.1   
26             7      147             76              0        0  39.4   
27             1       97             66             15      140  23.2   
28            13      145             82             19      110  22.2   
29             5      117             92              0        0  34.1   
..           ...      ...            ...            ...      ...   ...   
738            2       99             60             17      160  36.6   
739            1      102             74              0        0  39.5   
740           11      120             80             37      150  42.3   
741            3      102             44             20       94  30.8   
742            1      109             58             18      116  28.5   
743            9      140             94              0        0  32.7   
744           13      153             88             37      140  40.6   
745           12      100             84             33      105  30.0   
746            1      147             94             41        0  49.3   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   
752            3      108             62             24        0  26.0   
753            0      181             88             44      510  43.3   
754            8      154             78             32        0  32.4   
755            1      128             88             39      110  36.5   
756            7      137             90             41        0  32.0   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
760      

In [8]:
x=dataset.iloc[:,0:8].values

In [9]:
x

array([[   6.   ,  148.   ,   72.   , ...,   33.6  ,    0.627,   50.   ],
       [   1.   ,   85.   ,   66.   , ...,   26.6  ,    0.351,   31.   ],
       [   8.   ,  183.   ,   64.   , ...,   23.3  ,    0.672,   32.   ],
       ..., 
       [   5.   ,  121.   ,   72.   , ...,   26.2  ,    0.245,   30.   ],
       [   1.   ,  126.   ,   60.   , ...,   30.1  ,    0.349,   47.   ],
       [   1.   ,   93.   ,   70.   , ...,   30.4  ,    0.315,   23.   ]])

In [10]:
y=dataset.iloc[:,8].values

In [11]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1,

In [12]:
dataset.isnull()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0          False    False          False          False    False  False   
1          False    False          False          False    False  False   
2          False    False          False          False    False  False   
3          False    False          False          False    False  False   
4          False    False          False          False    False  False   
5          False    False          False          False    False  False   
6          False    False          False          False    False  False   
7          False    False          False          False    False  False   
8          False    False          False          False    False  False   
9          False    False          False          False    False  False   
10         False    False          False          False    False  False   
11         False    False          False          False    False  False   
12         False    False          False          False    False  False   
13         False    False          False          False    False  False   
14         False    False          False          False    False  False   
15         False    False          False          False    False  False   
16         False    False          False          False    False  False   
17         False    False          False          False    False  False   
18         False    False          False          False    False  False   
19         False    False          False          False    False  False   
20         False    False          False          False    False  False   
21         False    False          False          False    False  False   
22         False    False          False          False    False  False   
23         False    False          False          False    False  False   
24         False    False          False          False    False  False   
25         False    False          False          False    False  False   
26         False    False          False          False    False  False   
27         False    False          False          False    False  False   
28         False    False          False          False    False  False   
29         False    False          False          False    False  False   
..           ...      ...            ...            ...      ...    ...   
738        False    False          False          False    False  False   
739        False    False          False          False    False  False   
740        False    False          False          False    False  False   
741        False    False          False          False    False  False   
742        False    False          False          False    False  False   
743        False    False          False          False    False  False   
744        False    False          False          False    False  False   
745        False    False          False          False    False  False   
746        False    False          False          False    False  False   
747        False    False          False          False    False  False   
748        False    False          False          False    False  False   
749        False    False          False          False    False  False   
750        False    False          False          False    False  False   
751        False    False          False          False    False  False   
752        False    False          False          False    False  False   
753        False    False          False          False    False  False   
754        False    False          False          False    False  False   
755        False    False          False          False    False  False   
756        False    False          False          False    False  False   
757        False    False          False          False    False  False   
758        False    False          False          False    False  False   
759        False    False     

In [13]:
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [14]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train =sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [15]:
import keras
from keras.models import Sequential
from keras.layers import Dense


Using TensorFlow backend.


In [16]:
model=Sequential()

In [17]:
x_train.shape

(614, 8)

In [18]:
model.add(Dense(input_dim=8,init="random_uniform",activation='relu',output_dim=15))#input layer

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=8, kernel_initializer="random_uniform", units=15, activation="relu")`
  if __name__ == '__main__':


In [19]:
model.add(Dense(output_dim=8,init="random_uniform",activation='relu'))#hidden layer

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="random_uniform", units=8)`
  if __name__ == '__main__':


In [20]:
model.add(Dense(output_dim=1,init='random_uniform',activation='sigmoid'))#output layer

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", kernel_initializer="random_uniform", units=1)`
  if __name__ == '__main__':


In [21]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [22]:
#since it is a binary classification WE use binary cross entropy.

In [23]:
model.fit(x_train,y_train,epochs=100,batch_size=32)#epochs no of iteration 

Epoch 1/100
614/614 [==============================] - 0s 237us/step - loss: 0.6915 - acc: 0.6401
Epoch 2/100
614/614 [==============================] - 0s 140us/step - loss: 0.6873 - acc: 0.6401
Epoch 3/100
614/614 [==============================] - 0s 135us/step - loss: 0.6786 - acc: 0.6401
Epoch 4/100
614/614 [==============================] - 0s 144us/step - loss: 0.6604 - acc: 0.6401
Epoch 5/100
614/614 [==============================] - 0s 46us/step - loss: 0.6302 - acc: 0.6401
Epoch 6/100
614/614 [==============================] - 0s 142us/step - loss: 0.5936 - acc: 0.6433
Epoch 7/100
614/614 [==============================] - 0s 147us/step - loss: 0.5604 - acc: 0.7134
Epoch 8/100
614/614 [==============================] - 0s 46us/step - loss: 0.5366 - acc: 0.7622
Epoch 9/100
614/614 [==============================] - 0s 139us/step - loss: 0.5215 - acc: 0.7638
Epoch 10/100
614/614 [==============================] - 0s 152us/step - loss: 0.5101 - acc: 0.7590
Epoch 11/100
614/614 

In [24]:
y_pred = model.predict(x_test)

In [25]:
y_pred=(y_pred>0.5)

In [26]:
y_pred

array([[ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [

In [27]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [33]:
y_p=model.predict(sc.transform(np.array([[10,125,70,26,115,31.1,0.205,41]])))

In [34]:
y_p

array([[ 0.41035894]], dtype=float32)

In [35]:
y_p=(y_p>0.5)

In [36]:
y_p

array([[False]], dtype=bool)

In [32]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.80519480519480524

In [37]:
model.save("project.h5")

In [38]:
!tar -zcvf project.tgz project.h5

project.h5


In [39]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

In [40]:
wml_credentials={
    "access_key": "6zyBxUv5QATf_MhfUC0FNi0IyTXumOx4X7kkzVI5Bwt2",
  "instance_id": "b4d02699-577b-4ab9-9127-f7beb846f6fd",
  "password": "3e9745ed-da33-4f8d-ac44-3c96b2ea2616",
  "url": "https://eu-gb.ml.cloud.ibm.com",
  "username": "20eaa10b-4154-44ce-b5ff-6dc7f40b08d7"    
}

In [41]:
client=WatsonMachineLearningAPIClient(wml_credentials)


In [42]:
metadata={
    client.repository.ModelMetaNames.NAME:"keras.model",
     client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES:[{'name':'keras','version':'2.1.3'}],
     client.repository.ModelMetaNames.FRAMEWORK_NAME:"tensorflow",
     client.repository.ModelMetaNames.FRAMEWORK_VERSION:"1.5"
}

In [43]:
model_details=client.repository.store_model(model="project.tgz",meta_props=metadata)

In [44]:
client.repository.list_models()

------------------------------------  -----------  ------------------------  --------------
GUID                                  NAME         CREATED                   FRAMEWORK
0dc0313b-ac1b-4b79-9771-92e46a7be37b  keras.model  2019-05-21T07:34:24.875Z  tensorflow-1.5
b7042e3e-8854-4b31-b2e8-1b8e7554b35c  keras.model  2019-05-17T10:02:53.288Z  tensorflow-1.5
82df6095-622c-4754-ad82-106fd66392ad  keras.model  2019-05-17T10:01:53.168Z  tensorflow-1.5
------------------------------------  -----------  ------------------------  --------------


In [48]:
model_uid=model_details['metadata']['guid']
model_deploy=client.deployments.create(artifact_uid=model_uid,name="project_dia")




#######################################################################################

Synchronous deployment creation for uid: '0dc0313b-ac1b-4b79-9771-92e46a7be37b' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='db90388a-f781-4956-8708-637f363fd4d7'
------------------------------------------------------------------------------------------------




In [49]:
scoring_endpoint=client.deployments.get_scoring_url(model_deploy)

In [50]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/b4d02699-577b-4ab9-9127-f7beb846f6fd/deployments/db90388a-f781-4956-8708-637f363fd4d7/online'