In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [49]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_063c8c7ef9d84124a47dc8a6a3ad3478 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='LTRKr4XHWV_TMcfEpVKNjtQqmHvw1MgbM4X_R_zwd-5x',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_063c8c7ef9d84124a47dc8a6a3ad3478.get_object(Bucket='deeplearningproject-donotdelete-pr-alexj8kyq2vbyt',Key='data (1).csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df.head()



id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

      ...       texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0     ...               17.33           184.60      2019.0            0.1622   
1     ...               23.41           158.80      1956.0            0.1238   
2     ...               25.53           152.50      1709.0            0.1444   
3     ...               26.50            98.87       567.7            0.2098   
4     ...               16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [50]:
df.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean     ...       texture_worst  perimeter_worst  \
count     569.000000     ...          569.000000       569.000000   
mean        0.181162     ...           25.677223       107.261213   
std         0.027414     ...            6.146258        33.602542   
min         0.106000     ...           12.020000        50.410000   
25%         0.161900     ...           21.080000        84.110000   
50%         0.179200     ...           25.410000        97.660000   
75%         0.195700     ...           29.720000       125.400000   
max         0.304000     ...           49.540000       251.200000   

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000   
mean    880.583128          0.132369           0.254265         0.272188   
std     569.356993          0.022832           0.157336         0.208624   
min     185.200000          0.071170           0.027290         0.000000   
25%     515.300000          0.116600           0.147200         0.114500   
50%     686.500000          0.131300           0.211900         0.226700   
75%    1084.000000          0.146000           0.339100         0.382900   
max    4254.000000          0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [51]:
df.isnull().any()

id                         False
diagnosis                  False
radius_mean                False
texture_mean               False
perimeter_mean             False
area_mean                  False
smoothness_mean            False
compactness_mean           False
concavity_mean             False
concave points_mean        False
symmetry_mean              False
fractal_dimension_mean     False
radius_se                  False
texture_se                 False
perimeter_se               False
area_se                    False
smoothness_se              False
compactness_se             False
concavity_se               False
concave points_se          False
symmetry_se                False
fractal_dimension_se       False
radius_worst               False
texture_worst              False
perimeter_worst            False
area_worst                 False
smoothness_worst           False
compactness_worst          False
concavity_worst            False
concave points_worst       False
symmetry_w

In [52]:
y=df.iloc[:,1].values

In [96]:
x_train[2]

array([-0.16778028,  0.71464588, -0.19387105, -0.25539924, -0.63244883,
       -0.50278686, -0.49189629, -0.36906285,  0.01374189, -0.79419772,
       -0.59959192,  0.25866693, -0.54084065, -0.42328115, -0.87980701,
       -0.65225395, -0.33334744,  0.03169449, -0.49377709, -0.67098121,
       -0.22138004,  1.02260198, -0.23370102, -0.31134325, -0.70483428,
       -0.53047387, -0.18135392,  0.23344935, -0.04271939, -0.85592426])

In [54]:
y.reshape(-1,1)

array([['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['B'],
       ['B'],
       ['B'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['B'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['B'],
       ['M'],
       ['B'],
       ['B'],
       ['B'],
       ['B'],
       ['B'],
       ['M'],
       ['M'],
       ['B'],
       ['M'],
       ['M'],
       ['B'],
       ['B'],
       ['B'],
       ['B'],
       ['M'],
       ['B'],
       ['M'],
       ['M'],
       ['B'],
       ['B'],
       ['B'],
       ['B'],
       ['M'],
      

In [55]:
x=df.iloc[:,2:32].values


In [56]:
x

array([[  1.79900000e+01,   1.03800000e+01,   1.22800000e+02, ...,
          2.65400000e-01,   4.60100000e-01,   1.18900000e-01],
       [  2.05700000e+01,   1.77700000e+01,   1.32900000e+02, ...,
          1.86000000e-01,   2.75000000e-01,   8.90200000e-02],
       [  1.96900000e+01,   2.12500000e+01,   1.30000000e+02, ...,
          2.43000000e-01,   3.61300000e-01,   8.75800000e-02],
       ..., 
       [  1.66000000e+01,   2.80800000e+01,   1.08300000e+02, ...,
          1.41800000e-01,   2.21800000e-01,   7.82000000e-02],
       [  2.06000000e+01,   2.93300000e+01,   1.40100000e+02, ...,
          2.65000000e-01,   4.08700000e-01,   1.24000000e-01],
       [  7.76000000e+00,   2.45400000e+01,   4.79200000e+01, ...,
          0.00000000e+00,   2.87100000e-01,   7.03900000e-02]])

In [57]:
x.shape

(569, 30)

In [58]:
from sklearn.preprocessing import LabelEncoder 


In [59]:
lb1=LabelEncoder()
y=lb1.fit_transform(y)

In [60]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1,

In [61]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [62]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [63]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [64]:
model=Sequential()

In [65]:
model.add(Dense(10,input_dim=30))

In [66]:
model.add(Dense(10))

In [67]:
model.add(Dense(1,activation="sigmoid"))

In [68]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [69]:
model.fit(x_train,y_train,epochs=100,batch_size=32)

Epoch 1/100
455/455 [==============================] - 0s 285us/step - loss: 0.9357 - acc: 0.2813
Epoch 2/100
455/455 [==============================] - 0s 45us/step - loss: 0.6674 - acc: 0.5670
Epoch 3/100
455/455 [==============================] - 0s 45us/step - loss: 0.4988 - acc: 0.7868
Epoch 4/100
455/455 [==============================] - 0s 78us/step - loss: 0.3902 - acc: 0.8637
Epoch 5/100
455/455 [==============================] - 0s 45us/step - loss: 0.3100 - acc: 0.8967
Epoch 6/100
455/455 [==============================] - 0s 45us/step - loss: 0.2530 - acc: 0.9209
Epoch 7/100
455/455 [==============================] - 0s 108us/step - loss: 0.2097 - acc: 0.9363
Epoch 8/100
455/455 [==============================] - 0s 45us/step - loss: 0.1771 - acc: 0.9407
Epoch 9/100
455/455 [==============================] - 0s 43us/step - loss: 0.1517 - acc: 0.9495
Epoch 10/100
455/455 [==============================] - 0s 43us/step - loss: 0.1340 - acc: 0.9626
Epoch 11/100
455/455 [=====

455/455 [==============================] - 0s 44us/step - loss: 0.0464 - acc: 0.9912
Epoch 85/100
455/455 [==============================] - 0s 44us/step - loss: 0.0456 - acc: 0.9912
Epoch 86/100
455/455 [==============================] - 0s 106us/step - loss: 0.0452 - acc: 0.9912
Epoch 87/100
455/455 [==============================] - 0s 43us/step - loss: 0.0454 - acc: 0.9912
Epoch 88/100
455/455 [==============================] - 0s 44us/step - loss: 0.0448 - acc: 0.9912
Epoch 89/100
455/455 [==============================] - 0s 113us/step - loss: 0.0442 - acc: 0.9912
Epoch 90/100
455/455 [==============================] - 0s 44us/step - loss: 0.0442 - acc: 0.9912
Epoch 91/100
455/455 [==============================] - 0s 43us/step - loss: 0.0437 - acc: 0.9912
Epoch 92/100
455/455 [==============================] - 0s 43us/step - loss: 0.0436 - acc: 0.9912
Epoch 93/100
455/455 [==============================] - 0s 103us/step - loss: 0.0443 - acc: 0.9912
Epoch 94/100
455/455 [========

In [70]:
y_pred=model.predict(x_test)

In [71]:
score=model.evaluate(x_train,y_train)

455/455 [==============================] - 0s 61us/step


In [72]:
print('accuracy :'+str(score[1]*100))

accuracy :99.1208791209


In [73]:



y_pred=model.predict(x_test)
y_pred=(y_pred>0.5)
y_pred

array([[False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [

In [74]:
model.save("project.h5")

In [75]:
!tar -zcvf project.tgz project.h5

project.h5


In [76]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

In [77]:
kgf={
    "accesskey":"LmCcqPrfv6iJNBm8JpMml-FR7UzMng_5sHMUkPgjxGv8",
    "instance_id": "723b47aa-1cfc-4096-9aa4-f4164edabfef",
  "password": "14b7bdbf-ddc4-4c80-823f-bf64be74118b",
  "url": "https://eu-gb.ml.cloud.ibm.com",
  "username": "fc498606-2244-4781-a53e-845935a312d9"
}   


In [78]:
client=WatsonMachineLearningAPIClient(kgf)

In [79]:
metadata={
    client.repository.ModelMetaNames.NAME:"keras model",
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES:[{'name':'keras','version':'2.1.3'}],
     client.repository.ModelMetaNames.FRAMEWORK_NAME:"tensorflow",
     client.repository.ModelMetaNames.FRAMEWORK_VERSION:"1.5"
}

In [80]:
model_details=client.repository.store_model(model="project.tgz",meta_props=metadata)

In [81]:
client.repository.list_models()

------------------------------------  -----------  ------------------------  --------------
GUID                                  NAME         CREATED                   FRAMEWORK
2f827446-d9f9-4fa5-9a2e-d7b3b317b701  keras model  2019-05-24T18:09:28.121Z  tensorflow-1.5
23c4aa44-56d9-405e-afd8-7a2565d97e28  keras model  2019-05-24T18:07:17.729Z  tensorflow-1.5
1255b5db-91e9-4df1-ad1b-7dd337c9092b  keras model  2019-05-24T17:50:04.832Z  tensorflow-1.5
1985470b-81a5-4df1-acf5-290229ec8ff7  keras model  2019-05-24T07:26:47.461Z  tensorflow-1.5
8e6dc922-50d8-48ae-95a2-58b34d6d661f  keras model  2019-05-22T07:54:42.795Z  tensorflow-1.5
515b8f6e-2359-4ee5-a8df-6eb544394c4a  keras model  2019-05-17T10:03:41.685Z  tensorflow-1.5
------------------------------------  -----------  ------------------------  --------------


In [82]:
model_uid=model_details["metadata"]["guid"]
model_deploy=client.deployments.create(artifact_uid=model_uid,name='classification')



#######################################################################################

Synchronous deployment creation for uid: '2f827446-d9f9-4fa5-9a2e-d7b3b317b701' started

#######################################################################################


INITIALIZING
DEPLOY_IN_PROGRESS
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='dcbb9cf5-9348-4cad-b158-51dc4200d43d'
------------------------------------------------------------------------------------------------




In [83]:
scoring_endpoint=client.deployments.get_scoring_url(model_deploy)

In [84]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/723b47aa-1cfc-4096-9aa4-f4164edabfef/deployments/dcbb9cf5-9348-4cad-b158-51dc4200d43d/online'

In [85]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.96491228070175439

In [97]:
n=model.predict_classes((np.array([[-0.16778028,  0.71464588, -0.19387105, -0.25539924, -0.63244883,
       -0.50278686, -0.49189629, -0.36906285,  0.01374189, -0.79419772,
       -0.59959192,  0.25866693, -0.54084065, -0.42328115, -0.87980701,
       -0.65225395, -0.33334744,  0.03169449, -0.49377709, -0.67098121,
       -0.22138004,  1.02260198, -0.23370102, -0.31134325, -0.70483428,
       -0.53047387, -0.18135392,  0.23344935, -0.04271939, -0.85592426]])))

In [98]:
sc.transform(np.array([[9.504,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189]]))

array([[-1.30642051, -2.062581  ,  1.29602947,  1.00675312,  1.65446818,
         3.40545988,  2.75178408,  2.61073574,  2.28401635,  2.3185689 ,
         2.40497343, -0.55805077,  2.73229564,  2.37197354, -0.21688153,
         1.4477612 ,  0.74914564,  0.68933052,  1.10331953,  0.97465928,
         1.92027056, -1.35208145,  2.34910987,  2.04933964,  1.33466412,
         2.84030385,  2.25559979,  2.33766767,  2.7733405 ,  2.18393991]])

In [99]:
n

array([[0]], dtype=int32)

In [6]:
client.deployments.

------------------------------------  --------------  ------  --------------  ------------------------  --------------  -------------
GUID                                  NAME            TYPE    STATE           CREATED                   FRAMEWORK       ARTIFACT TYPE
39a2bc19-ed10-4d5b-83d5-954ac90d004a  classification  online  DEPLOY_SUCCESS  2019-05-24T17:50:09.135Z  tensorflow-1.5  model
12bf78e3-98b6-44b9-a6f9-1caa66f28e7c  classification  online  DEPLOY_SUCCESS  2019-05-24T07:26:50.291Z  tensorflow-1.5  model
ff487534-e5ab-40ad-90dd-c6788603b1f6  classification  online  DEPLOY_SUCCESS  2019-05-22T07:56:46.244Z  tensorflow-1.5  model
6647bc44-767b-4bd5-9b96-8128a12dae0c  ann_reg         online  DEPLOY_SUCCESS  2019-05-17T10:13:24.552Z  tensorflow-1.5  model
------------------------------------  --------------  ------  --------------  ------------------------  --------------  -------------
