In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import keras

Using TensorFlow backend.


In [2]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_e128639181ed4a4390362d2f535c9356 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='p4XgC5YHM_smjoBUmH5K7OmCKkComFPtaUCMEcRnfkzS',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_e128639181ed4a4390362d2f535c9356.get_object(Bucket='deeplearningproject-donotdelete-pr-402terqi0fdjlf',Key='housingdata.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df= pd.read_csv(body)
df.head()

df.shape

(505, 14)

In [3]:
df.head()

0.00632   18  2.31  0  0.538  6.575  65.2    4.09  1  296  15.3   396.9  \
0  0.02731  0.0  7.07  0  0.469  6.421  78.9  4.9671  2  242  17.8  396.90   
1  0.02729  0.0  7.07  0  0.469  7.185  61.1  4.9671  2  242  17.8  392.83   
2  0.03237  0.0  2.18  0  0.458  6.998  45.8  6.0622  3  222  18.7  394.63   
3  0.06905  0.0  2.18  0  0.458  7.147  54.2  6.0622  3  222  18.7  396.90   
4  0.02985  0.0  2.18  0  0.458  6.430  58.7  6.0622  3  222  18.7  394.12   

   4.98    24  
0  9.14  21.6  
1  4.03  34.7  
2  2.94  33.4  
3  5.33  36.2  
4  5.21  28.7

In [4]:
##columns = ['Employee ID','Unnamed: 34','Unnamed: 35','Unnamed: 36','Unnamed: 37','Unnamed: 38','Unnamed: 39','Unnamed: 40','Unnamed: 41','Unnamed: 42']
##df.drop(columns, inplace=True, axis=1)
df.shape

(505, 14)

In [5]:
import sklearn

In [6]:
from sklearn.preprocessing import LabelEncoder
lr=LabelEncoder()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 14 columns):
0.00632    505 non-null float64
18         505 non-null float64
2.31       505 non-null float64
0          505 non-null int64
0.538      505 non-null float64
6.575      505 non-null float64
65.2       505 non-null float64
4.09       505 non-null float64
1          505 non-null int64
296        505 non-null int64
15.3       505 non-null float64
396.9      505 non-null float64
4.98       505 non-null float64
24         505 non-null float64
dtypes: float64(11), int64(3)
memory usage: 55.3 KB


In [8]:
for c in df.columns:
    if df[c].dtype!='int64':
        df[c]=lr.fit_transform(df[c])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 14 columns):
0.00632    505 non-null int64
18         505 non-null int64
2.31       505 non-null int64
0          505 non-null int64
0.538      505 non-null int64
6.575      505 non-null int64
65.2       505 non-null int64
4.09       505 non-null int64
1          505 non-null int64
296        505 non-null int64
15.3       505 non-null int64
396.9      505 non-null int64
4.98       505 non-null int64
24         505 non-null int64
dtypes: int64(14)
memory usage: 55.3 KB


In [10]:
df.head()

0.00632  18  2.31  0  0.538  6.575  65.2  4.09  1  296  15.3  396.9  4.98  \
0       22   0    55  0     36    279   225   332  2  242    23    356   160   
1       21   0    55  0     36    399   159   332  2  242    23    271    28   
2       31   0    16  0     33    382   112   360  3  222    31    311     6   
3      109   0    16  0     33    394   139   360  3  222    31    356    63   
4       26   0    16  0     33    282   153   360  3  222    31    302    59   

    24  
0  113  
1  196  
2  193  
3  203  
4  165

In [11]:
df['0'].value_counts()

0    470
1     35
Name: 0, dtype: int64

In [12]:
y=df.pop('0')

In [13]:
x=df

In [14]:
x.shape,y.shape

((505, 13), (505,))

In [15]:
# print(df.shape)
# x=df.iloc[:,:13]
# x.shape

In [16]:
# y=df.iloc[:,13].values
# y

In [17]:
from keras.utils import to_categorical
target=to_categorical(y)
target

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       ..., 
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.]])

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,target,test_size=0.3)

In [19]:
x_train.shape,x_test.shape,y_test.shape,y_train.shape

((353, 13), (152, 13), (152, 2), (353, 2))

In [23]:
from keras import Sequential
from keras.layers import Dense
mod=Sequential()
mod.add(Dense(100,input_shape=(13,)))
mod.add(Dense(200,activation='relu'))
mod.add(Dense(200,activation='relu'))
mod.add(Dense(200,activation='relu'))
mod.add(Dense(200,activation='relu'))
mod.add(Dense(200,activation='relu'))
mod.add(Dense(200,activation='relu'))
mod.add(Dense(2,activation='sigmoid'))
mod.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [24]:
mod.fit(x,target,epochs=200)

Epoch 1/200
505/505 [==============================] - 1s 1ms/step - loss: 1.2903 - acc: 0.8871
Epoch 2/200
505/505 [==============================] - 0s 356us/step - loss: 1.1110 - acc: 0.9307
Epoch 3/200
505/505 [==============================] - 0s 246us/step - loss: 1.1110 - acc: 0.9307
Epoch 4/200
505/505 [==============================] - 0s 363us/step - loss: 1.1110 - acc: 0.9307
Epoch 5/200
505/505 [==============================] - 0s 365us/step - loss: 1.1110 - acc: 0.9307
Epoch 6/200
505/505 [==============================] - 0s 248us/step - loss: 1.1110 - acc: 0.9307
Epoch 7/200
505/505 [==============================] - 0s 366us/step - loss: 1.1110 - acc: 0.9307
Epoch 8/200
505/505 [==============================] - 0s 364us/step - loss: 1.1110 - acc: 0.9307
Epoch 9/200
505/505 [==============================] - 0s 253us/step - loss: 1.1110 - acc: 0.9307
Epoch 10/200
505/505 [==============================] - 0s 364us/step - loss: 1.1110 - acc: 0.9307
Epoch 11/200
505/505 

505/505 [==============================] - 0s 246us/step - loss: 1.1110 - acc: 0.9307
Epoch 84/200
505/505 [==============================] - 0s 365us/step - loss: 1.1110 - acc: 0.9307
Epoch 85/200
505/505 [==============================] - 0s 372us/step - loss: 1.1110 - acc: 0.9307
Epoch 86/200
505/505 [==============================] - 0s 249us/step - loss: 1.1110 - acc: 0.9307
Epoch 87/200
505/505 [==============================] - 0s 369us/step - loss: 1.1110 - acc: 0.9307
Epoch 88/200
505/505 [==============================] - 0s 363us/step - loss: 1.1110 - acc: 0.9307
Epoch 89/200
505/505 [==============================] - 0s 247us/step - loss: 1.1110 - acc: 0.9307
Epoch 90/200
505/505 [==============================] - 0s 375us/step - loss: 1.1110 - acc: 0.9307
Epoch 91/200
505/505 [==============================] - 0s 362us/step - loss: 1.1110 - acc: 0.9307
Epoch 92/200
505/505 [==============================] - 0s 246us/step - loss: 1.1110 - acc: 0.9307
Epoch 93/200
505/505 [=

505/505 [==============================] - 0s 259us/step - loss: 1.1110 - acc: 0.9307
Epoch 166/200
505/505 [==============================] - 0s 359us/step - loss: 1.1110 - acc: 0.9307
Epoch 167/200
505/505 [==============================] - 0s 262us/step - loss: 1.1110 - acc: 0.9307
Epoch 168/200
505/505 [==============================] - 0s 263us/step - loss: 1.1110 - acc: 0.9307
Epoch 169/200
505/505 [==============================] - 0s 359us/step - loss: 1.1110 - acc: 0.9307
Epoch 170/200
505/505 [==============================] - 0s 248us/step - loss: 1.1110 - acc: 0.9307
Epoch 171/200
505/505 [==============================] - 0s 362us/step - loss: 1.1110 - acc: 0.9307
Epoch 172/200
505/505 [==============================] - 0s 361us/step - loss: 1.1110 - acc: 0.9307
Epoch 173/200
505/505 [==============================] - 0s 251us/step - loss: 1.1110 - acc: 0.9307
Epoch 174/200
505/505 [==============================] - 0s 363us/step - loss: 1.1110 - acc: 0.9307
Epoch 175/200


In [25]:
y_pred = mod.predict(x_test)
y_pred

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,

In [26]:
y_pred=y_pred[y_pred>0.5]

In [27]:
y_pred

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

In [28]:
mod.save('employee_attrition.h5')

In [29]:
!tar -zcvf employee_attrition.tgz employee_attrition.h5

employee_attrition.h5


In [30]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [31]:
wml_credentials={"accesskey": "jNtPOYP0I7WJe0VybGQRRkB-80kM40ASai-yy3imkZ_9"
 , "instance_id": "b6d8c64d-e884-45fe-98b0-014f5d1f0249",
 "password": "88e6e6e9-2b3d-4a9a-840e-c3931ae1c4a6",
 "url": "https://eu-gb.ml.cloud.ibm.com",
 "username": "77bf6613-1539-4ff8-9666-4ef865e4c547"}

In [32]:
client=WatsonMachineLearningAPIClient(wml_credentials)

In [33]:
metadata={
    client.repository.ModelMetaNames.NAME : "keras model",
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES: [{'name':'keras', 'version':'2.1.3'}],
    client.repository.ModelMetaNames.FRAMEWORK_NAME:"tensorflow",
    client.repository.ModelMetaNames.FRAMEWORK_VERSION: "1.5",
}

In [34]:
model_details=client.repository.store_model(model="employee_attrition.tgz",meta_props=metadata)

In [35]:
client.repository.list_models()

------------------------------------  -----------  ------------------------  --------------
GUID                                  NAME         CREATED                   FRAMEWORK
50336536-916d-4ada-b082-72c1b381dae9  keras model  2019-05-25T06:14:53.304Z  tensorflow-1.5
9768806d-b4e8-40eb-91f7-4861f3338ca4  keras model  2019-05-24T06:49:56.189Z  tensorflow-1.5
574f5cc4-2827-47da-b9f9-4847def09564  keras model  2019-05-17T10:27:00.335Z  tensorflow-1.5
------------------------------------  -----------  ------------------------  --------------


In [36]:
model_uid=model_details['metadata']['guid']
model_deploy=client.deployments.create(artifact_uid=model_uid,name="ann_reg")




#######################################################################################

Synchronous deployment creation for uid: '50336536-916d-4ada-b082-72c1b381dae9' started

#######################################################################################


INITIALIZING
DEPLOY_IN_PROGRESS
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='4b3967b1-cd41-4b1c-baf5-f9384f0a9c9a'
------------------------------------------------------------------------------------------------




In [37]:
scoring_endpoint=client.deployments.get_scoring_url(model_deploy)

In [38]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/b6d8c64d-e884-45fe-98b0-014f5d1f0249/deployments/4b3967b1-cd41-4b1c-baf5-f9384f0a9c9a/online'

In [40]:
client.deployments.delete('4b3967b1-cd41-4b1c-baf5-f9384f0a9c9a')

'SUCCESS'